export const lightTheme = {
  name: 'light',
  colors: {
    background: '#FEFFFE',
    backgroundSoft: '#FFF6EE',
    surface: '#FFFFFF',
    surfaceAlt: '#F4F1EC',
    primary: '#D97F5C',
    primaryHover: '#C26A47',
    primaryLight: '#FEBE92',
    primarySoft: '#FFCAA1',
    accent: '#96CAB4',
    accentLight: '#CFE5D5',
    info: '#D4F3FF',
    text: '#602E23',
    textSoft: '#7A4A3D',
    textMuted: '#9C8378',
    border: '#EADBCB',
    cardBg: '#F4EEE7',
    shadow: 'rgba(96, 46, 35, 0.08)',
  },
};

export const darkTheme = {
  name: 'dark',
  colors: {
    background: '#161616',
    backgroundSoft: '#1E1E1E',
    surface: '#1F1F1F',
    surfaceAlt: '#262626',
    primary: '#D97F5C',
    primaryHover: '#E89570',
    primaryLight: '#FEBE92',
    primarySoft: '#FFCAA1',
    accent: '#96CAB4',
    accentLight: '#CFE5D5',
    info: '#D4F3FF',
    text: '#FEFFFE',
    textSoft: '#E0D6CE',
    textMuted: '#9A9A9A',
    border: '#3A3A3A',
    cardBg: '#1F1F1F',
    shadow: 'rgba(217, 127, 92, 0.15)',
  },
};
